name: Release

on:
  push:
    branches:
      - main
    tags:
    - "v*"

env:
  IMAGE_NAME: helm

jobs:
  # Push image to GitHub Packages.
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v5

    - name: Log in to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Log in to quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_IO_USERNAME }}
        password: ${{ secrets.QUAY_IO_PASSWORD }}

    - name: Set image tag from Git ref
      run: |
        # Strip git ref prefix from version
        IMAGE_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && IMAGE_TAG=$(echo $IMAGE_TAG | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$IMAGE_TAG" == "main" ] && IMAGE_TAG=latest

        echo "IMAGE_TAG=${IMAGE_TAG}" | tee -a $GITHUB_ENV

    - name: Build docker image
      run: make docker-build

    - name: Push docker image
      run: make docker-push
