name: Master

on:
  push:
    branches:
    - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker hub
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}"  -p "${{ secrets.DOCKER_PASSWORD }}"  docker.io
    - name: Login to quay.io
      run: docker login -u "${{ secrets.QUAY_IO_USERNAME }}" -p "${{ secrets.QUAY_IO_PASSWORD }}" quay.io

    - name: Build docker image
      run: make docker-build

    - name: Push tagged docker image
      run: make docker-push
