name: Release

on:
  push:
    tags:
    - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to docker.io
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to quay.io
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_IO_USERNAME }}
        password: ${{ secrets.QUAY_IO_PASSWORD }}

    - name: Set version from tag
      run: echo IMAGE_TAG=$(echo ${GITHUB_REF#refs/tags/}) >> $GITHUB_ENV

    - name: Build docker image
      run: make docker-build

    - name: Push docker image
      run: make docker-push
